spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/BlogBase
    username: postgres
    password: G85boq18Yh?/-
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update